### ISSUE TITLE
Connection not found

### ISSUE THREAD

**Issue by fwartner** [ben8p/home-assistant-bunq-balance-sensors#12]
Trying to integrate Bunq to my Home Assistant instance. But every single time since the update (I followed all the steps for a clean setup) it fails by telling me "Connection not found" on the Bunq website..

Any ideas?

<img width="1270" alt="CleanShot 2023-06-17 at 00 05 22@2x" src="https://github.com/ben8p/home-assistant-bunq-balance-sensors/assets/6692500/5bbe94f2-df82-4366-81cd-8bac290ee067">

**Comment by ben8p** [comment]
@fwartner this usually occurs if you didn't specify the correct redirect url.
Make sure to use exactly `https://my.home-assistant.io/redirect/oauth/`
(you could also try with the trailing `/`)

**Comment by fwartner** [comment]
![image](https://github.com/ben8p/home-assistant-bunq-balance-sensors/assets/6692500/861729ef-916a-4833-9020-0fddc8b45101)

I did..

**Comment by fwartner** [comment]
Without the trailing slash it works :D

**Comment by ben8p** [comment]
Awesome, thanks.
I will update the documentation

**Comment by jpduyx** [comment]
I am also getting connection not found error from bunq


And tried to do some troubleshooting. 

The my.home-assistant.io/redirect/author url says it is a non existing URL (while the my integration was working for my home assistant for other URLs ... ) and then the my website gave me options to make an URL to some app or so ... I didn't understand what exactly to do there and I couldn't find an option to make a link to the bunq add-on or something that looks like oauth. 

So to bypass this during troubleshooting I removed the "my" integration and restarted ha and only use the address of home assistant how I connect to it through my VPN. 

http://myinternaladress:8123/auth/external/callback

When I go to that address directly it gives me a white page with: "Missing state parameter" ... Okay. The state should probably come from the oauth redirect. 


But bunq gives me the "connection not found" error. 

Then
I tried to use the URL that bunq put as redirect URL (same address but including the state parameter)  in the browser and that gave me a 404 error. 

When my home assistant gives me a 404 error on the url that bunq tries to redirect to perhaps that makes bunq give me the "connection not found"? Or is bunq unable to reach my home assistant because it is not publicly available at all?


I have 2 questions:

- is it required that my home assistant is publicly accessible ? Mine is not and I didn't see any requirements that it should be, to use oauth or this addon but to be sure. 
- can this integration also be configured manually (and how)? I see that another user had found a catch 22 that the redirect URL is not available when there is no addonthat is using the url and installing the add-on fails because there is no URL. 

https://community.home-assistant.io/t/solved-404-on-auth-external-callback/245070


Thank you
